server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 1KB
  http2:
    enabled: true
  undertow:
    accesslog:
      enabled: true
      dir: undertow-accesslog
      pattern: '%t %I %r %s %b %D'
  servlet:
    context-path: /apitest

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/Course/H2/course-db;DB_CLOSE_DELAY=10;AUTO_RECONNECT=TRUE;CIPHER=AES;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password: 'x x'

  hibernate:
    ddl-auto: create-drop
    properties:
      hibernate.format_sql: false
      hibernate.generate_statistics: false
      hibernate.query.immutable_entity_update_query_handling_mode: exception
    open-in-view: false


  profiles:
    active: dev
    #include: optional

custom:
  name: neng

---
spring:
  profiles: dev
custom:
  name: neng-dev
  email: neng@gmail.com
---
spring:
  profiles: test
custom:
  name: neng-test
  email: neng@gm
---
spring:
  profiles: optional
custom:
  tel: 0972232555
